/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, InstantiateMsg, ConfigMsg, ExecuteMsg, RequestedJob, Uint64, Uint128, Int64, Int128, PRNG, RequestMsg, GenerateMsg, AddWhitelistedAddress, RemoveWhitelistedAddress, QueryMsg, WhitelistedAddressesResponse, ConfigResponse, Config, RequestStatusEnum, QueryRequestResponse, RequestStatus } from "./CwRandom.types";
export interface CwRandomReadOnlyInterface {
  contractAddress: string;
  queryConfig: () => Promise<ConfigResponse>;
  queryRequest: ({
    id
  }: {
    id: string;
  }) => Promise<QueryRequestResponse>;
  getWhitelist: () => Promise<WhitelistedAddressesResponse>;
}
export class CwRandomQueryClient implements CwRandomReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.queryConfig = this.queryConfig.bind(this);
    this.queryRequest = this.queryRequest.bind(this);
    this.getWhitelist = this.getWhitelist.bind(this);
  }
  queryConfig = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_config: {}
    });
  };
  queryRequest = async ({
    id
  }: {
    id: string;
  }): Promise<QueryRequestResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_request: {
        id
      }
    });
  };
  getWhitelist = async (): Promise<WhitelistedAddressesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_whitelist: {}
    });
  };
}
export interface CwRandomInterface extends CwRandomReadOnlyInterface {
  contractAddress: string;
  sender: string;
  setConfig: ({
    denomAccepted,
    gasOffset,
    gasPricePerJob,
    gasToTokenRatio,
    maxGasPerBlock,
    maxJobPerRequest,
    maxNumberForJob,
    maxRecipients,
    operator
  }: {
    denomAccepted: string;
    gasOffset: string;
    gasPricePerJob: string;
    gasToTokenRatio: string;
    maxGasPerBlock: string;
    maxJobPerRequest: number;
    maxNumberForJob: number;
    maxRecipients: number;
    operator?: Addr;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  request: ({
    gasLimit,
    height,
    jobs,
    prng,
    recipients,
    responseId
  }: {
    gasLimit: string;
    height?: string;
    jobs: RequestedJob[];
    prng?: PRNG;
    recipients?: Addr[];
    responseId: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  generate: ({
    heightId,
    randomness
  }: {
    heightId?: string;
    randomness?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  addWhitelistedAddressMsg: ({
    addresses
  }: {
    addresses: Addr[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  removeWhitelistedAddressMsg: ({
    addresses
  }: {
    addresses: Addr[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class CwRandomClient extends CwRandomQueryClient implements CwRandomInterface {
  client: SigningCosmWasmClient = {} as SigningCosmWasmClient;
  sender: string;
  contractAddress: string = "";
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setConfig = this.setConfig.bind(this);
    this.request = this.request.bind(this);
    this.generate = this.generate.bind(this);
    this.addWhitelistedAddressMsg = this.addWhitelistedAddressMsg.bind(this);
    this.removeWhitelistedAddressMsg = this.removeWhitelistedAddressMsg.bind(this);
  }
  setConfig = async ({
    denomAccepted,
    gasOffset,
    gasPricePerJob,
    gasToTokenRatio,
    maxGasPerBlock,
    maxJobPerRequest,
    maxNumberForJob,
    maxRecipients,
    operator
  }: {
    denomAccepted: string;
    gasOffset: string;
    gasPricePerJob: string;
    gasToTokenRatio: string;
    maxGasPerBlock: string;
    maxJobPerRequest: number;
    maxNumberForJob: number;
    maxRecipients: number;
    operator?: Addr;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_config: {
        denom_accepted: denomAccepted,
        gas_offset: gasOffset,
        gas_price_per_job: gasPricePerJob,
        gas_to_token_ratio: gasToTokenRatio,
        max_gas_per_block: maxGasPerBlock,
        max_job_per_request: maxJobPerRequest,
        max_number_for_job: maxNumberForJob,
        max_recipients: maxRecipients,
        operator
      }
    }, fee_, memo_, funds_);
  };
  request = async ({
    gasLimit,
    height,
    jobs,
    prng,
    recipients,
    responseId
  }: {
    gasLimit: string;
    height?: string;
    jobs: RequestedJob[];
    prng?: PRNG;
    recipients?: Addr[];
    responseId: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      request: {
        gas_limit: gasLimit,
        height,
        jobs,
        prng,
        recipients,
        response_id: responseId
      }
    }, fee_, memo_, funds_);
  };
  generate = async ({
    heightId,
    randomness
  }: {
    heightId?: string;
    randomness?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      generate: {
        height_id: heightId,
        randomness
      }
    }, fee_, memo_, funds_);
  };
  addWhitelistedAddressMsg = async ({
    addresses
  }: {
    addresses: Addr[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_whitelisted_address_msg: {
        addresses
      }
    }, fee_, memo_, funds_);
  };
  removeWhitelistedAddressMsg = async ({
    addresses
  }: {
    addresses: Addr[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_whitelisted_address_msg: {
        addresses
      }
    }, fee_, memo_, funds_);
  };
}