/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Addr, InstantiateMsg, ConfigMsg, ExecuteMsg, RequestedJob, Uint64, Uint128, Int64, Int128, PRNG, RequestMsg, GenerateMsg, AddWhitelistedAddress, RemoveWhitelistedAddress, QueryMsg, WhitelistedAddressesResponse, ConfigResponse, Config, RequestStatusEnum, QueryRequestResponse, RequestStatus } from "./CwRandom.types";
export interface CwRandomMsg {
  contractAddress: string;
  sender: string;
  setConfig: ({
    denomAccepted,
    gasOffset,
    gasPricePerJob,
    gasToTokenRatio,
    maxGasPerBlock,
    maxJobPerRequest,
    maxNumberForJob,
    maxRecipients,
    operator
  }: {
    denomAccepted: string;
    gasOffset: string;
    gasPricePerJob: string;
    gasToTokenRatio: string;
    maxGasPerBlock: string;
    maxJobPerRequest: number;
    maxNumberForJob: number;
    maxRecipients: number;
    operator?: Addr;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  request: ({
    gasLimit,
    height,
    jobs,
    prng,
    recipients,
    responseId
  }: {
    gasLimit: string;
    height?: string;
    jobs: RequestedJob[];
    prng?: PRNG;
    recipients?: Addr[];
    responseId: string;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  generate: ({
    heightId,
    randomness
  }: {
    heightId?: string;
    randomness?: string;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  addWhitelistedAddressMsg: ({
    addresses
  }: {
    addresses: Addr[];
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  removeWhitelistedAddressMsg: ({
    addresses
  }: {
    addresses: Addr[];
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class CwRandomMsgComposer implements CwRandomMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setConfig = this.setConfig.bind(this);
    this.request = this.request.bind(this);
    this.generate = this.generate.bind(this);
    this.addWhitelistedAddressMsg = this.addWhitelistedAddressMsg.bind(this);
    this.removeWhitelistedAddressMsg = this.removeWhitelistedAddressMsg.bind(this);
  }
  setConfig = ({
    denomAccepted,
    gasOffset,
    gasPricePerJob,
    gasToTokenRatio,
    maxGasPerBlock,
    maxJobPerRequest,
    maxNumberForJob,
    maxRecipients,
    operator
  }: {
    denomAccepted: string;
    gasOffset: string;
    gasPricePerJob: string;
    gasToTokenRatio: string;
    maxGasPerBlock: string;
    maxJobPerRequest: number;
    maxNumberForJob: number;
    maxRecipients: number;
    operator?: Addr;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_config: {
            denom_accepted: denomAccepted,
            gas_offset: gasOffset,
            gas_price_per_job: gasPricePerJob,
            gas_to_token_ratio: gasToTokenRatio,
            max_gas_per_block: maxGasPerBlock,
            max_job_per_request: maxJobPerRequest,
            max_number_for_job: maxNumberForJob,
            max_recipients: maxRecipients,
            operator
          }
        })),
        funds: funds_
      })
    };
  };
  request = ({
    gasLimit,
    height,
    jobs,
    prng,
    recipients,
    responseId
  }: {
    gasLimit: string;
    height?: string;
    jobs: RequestedJob[];
    prng?: PRNG;
    recipients?: Addr[];
    responseId: string;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          request: {
            gas_limit: gasLimit,
            height,
            jobs,
            prng,
            recipients,
            response_id: responseId
          }
        })),
        funds: funds_
      })
    };
  };
  generate = ({
    heightId,
    randomness
  }: {
    heightId?: string;
    randomness?: string;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          generate: {
            height_id: heightId,
            randomness
          }
        })),
        funds: funds_
      })
    };
  };
  addWhitelistedAddressMsg = ({
    addresses
  }: {
    addresses: Addr[];
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          add_whitelisted_address_msg: {
            addresses
          }
        })),
        funds: funds_
      })
    };
  };
  removeWhitelistedAddressMsg = ({
    addresses
  }: {
    addresses: Addr[];
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_whitelisted_address_msg: {
            addresses
          }
        })),
        funds: funds_
      })
    };
  };
}