/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  config: ConfigMsg;
  starting_seed?: string | null;
}
export interface ConfigMsg {
  denom_accepted: string;
  gas_offset: string;
  gas_price_per_job: string;
  gas_to_token_ratio: string;
  max_gas_per_block: string;
  max_job_per_request: number;
  max_number_for_job: number;
  max_recipients: number;
  operator?: Addr | null;
}
export type ExecuteMsg = {
  set_config: ConfigMsg;
} | {
  request: RequestMsg;
} | {
  generate: GenerateMsg;
} | {
  add_whitelisted_address_msg: AddWhitelistedAddress;
} | {
  remove_whitelisted_address_msg: RemoveWhitelistedAddress;
};
export type RequestedJob = {
  u8: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  u16: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  u32: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  u64: {
    max?: Uint64 | null;
    min?: Uint64 | null;
    n: number;
  };
} | {
  u128: {
    max?: Uint128 | null;
    min?: Uint128 | null;
    n: number;
  };
} | {
  i8: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  i16: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  i32: {
    max?: number | null;
    min?: number | null;
    n: number;
  };
} | {
  i64: {
    max?: Int64 | null;
    min?: Int64 | null;
    n: number;
  };
} | {
  i128: {
    max?: Int128 | null;
    min?: Int128 | null;
    n: number;
  };
};
export type Uint64 = string;
export type Uint128 = string;
export type Int64 = string;
export type Int128 = string;
export type PRNG = "cha_cha8" | "cha_cha12" | "cha_cha20";
export interface RequestMsg {
  gas_limit: string;
  height?: string | null;
  jobs: RequestedJob[];
  prng?: PRNG | null;
  recipients?: Addr[] | null;
  response_id: string;
}
export interface GenerateMsg {
  height_id?: string | null;
  randomness?: string | null;
}
export interface AddWhitelistedAddress {
  addresses: Addr[];
}
export interface RemoveWhitelistedAddress {
  addresses: Addr[];
}
export type QueryMsg = {
  query_config: {};
} | {
  query_request: {
    id: string;
  };
} | {
  get_whitelist: {};
};
export interface WhitelistedAddressesResponse {
  addresses: Addr[];
}
export type ConfigResponse = Config;
export interface Config {
  denom_accepted: string;
  gas_offset: Uint64;
  gas_price_per_job: Uint64;
  gas_to_token_ratio: Uint64;
  max_gas_per_block: Uint64;
  max_job_per_request: number;
  max_number_for_job: number;
  max_recipients: number;
  operator?: Addr | null;
}
export type RequestStatusEnum = "pending" | "completed" | "failed" | "failed_client_side";
export interface QueryRequestResponse {
  id: string;
  status: RequestStatus;
}
export interface RequestStatus {
  error_message?: string | null;
  height_completed?: Uint64 | null;
  height_requested: Uint64;
  height_serving: Uint64;
  status: RequestStatusEnum;
}