/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Addr, InstantiateMsg, ConfigMsg, ExecuteMsg, GameType, Uint64, JobResult, Uint128, Int64, Int128, Token, PlayRequestMsg, ExactNumberGame, HighLowGame, ReceiveRandomnessMsg, FetchRandomCWConfigMsg, WithdrawMsg, QueryMsg, UserGamesQueryMsg, ConfigResponse, Config, QueryPlayResponse, GameStatus, GameRequest, QueryUserGamesResponse } from "./RollADice.types";
export interface RollADiceMsg {
  contractAddress: string;
  sender: string;
  setConfig: ({
    acceptedDenom,
    disabled,
    feePercentage,
    gasLimit,
    maxBet,
    minBet,
    operator,
    randomCwAddress
  }: {
    acceptedDenom: string;
    disabled: boolean;
    feePercentage: string;
    gasLimit: string;
    maxBet: string;
    minBet: string;
    operator?: Addr;
    randomCwAddress: Addr;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  playRequest: ({
    gameType
  }: {
    gameType: GameType;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  receiveRandomness: ({
    id,
    results
  }: {
    id: Uint64;
    results: JobResult[];
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  fetchRandomCWConfig: (funds_?: Coin[]) => MsgExecuteContractEncodeObject;
  withdraw: ({
    amount,
    token
  }: {
    amount: string;
    token: Token;
  }, funds_?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class RollADiceMsgComposer implements RollADiceMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setConfig = this.setConfig.bind(this);
    this.playRequest = this.playRequest.bind(this);
    this.receiveRandomness = this.receiveRandomness.bind(this);
    this.fetchRandomCWConfig = this.fetchRandomCWConfig.bind(this);
    this.withdraw = this.withdraw.bind(this);
  }
  setConfig = ({
    acceptedDenom,
    disabled,
    feePercentage,
    gasLimit,
    maxBet,
    minBet,
    operator,
    randomCwAddress
  }: {
    acceptedDenom: string;
    disabled: boolean;
    feePercentage: string;
    gasLimit: string;
    maxBet: string;
    minBet: string;
    operator?: Addr;
    randomCwAddress: Addr;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_config: {
            accepted_denom: acceptedDenom,
            disabled,
            fee_percentage: feePercentage,
            gas_limit: gasLimit,
            max_bet: maxBet,
            min_bet: minBet,
            operator,
            random_cw_address: randomCwAddress
          }
        })),
        funds: funds_
      })
    };
  };
  playRequest = ({
    gameType
  }: {
    gameType: GameType;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          play_request: {
            game_type: gameType
          }
        })),
        funds: funds_
      })
    };
  };
  receiveRandomness = ({
    id,
    results
  }: {
    id: Uint64;
    results: JobResult[];
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          receive_randomness: {
            id,
            results
          }
        })),
        funds: funds_
      })
    };
  };
  fetchRandomCWConfig = (funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          fetch_random_c_w_config: {}
        })),
        funds: funds_
      })
    };
  };
  withdraw = ({
    amount,
    token
  }: {
    amount: string;
    token: Token;
  }, funds_?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw: {
            amount,
            token
          }
        })),
        funds: funds_
      })
    };
  };
}