/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, InstantiateMsg, ConfigMsg, ExecuteMsg, GameType, Uint64, JobResult, Uint128, Int64, Int128, Token, PlayRequestMsg, ExactNumberGame, HighLowGame, ReceiveRandomnessMsg, FetchRandomCWConfigMsg, WithdrawMsg, QueryMsg, UserGamesQueryMsg, ConfigResponse, Config, QueryPlayResponse, GameStatus, GameRequest, QueryUserGamesResponse } from "./RollADice.types";
export interface RollADiceReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  queryGame: ({
    id
  }: {
    id: string;
  }) => Promise<QueryPlayResponse>;
  userGamesQuery: ({
    cursor,
    limit,
    userAddress
  }: {
    cursor?: number;
    limit: number;
    userAddress: Addr;
  }) => Promise<QueryUserGamesResponse>;
}
export class RollADiceQueryClient implements RollADiceReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.queryGame = this.queryGame.bind(this);
    this.userGamesQuery = this.userGamesQuery.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  queryGame = async ({
    id
  }: {
    id: string;
  }): Promise<QueryPlayResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_game: {
        id
      }
    });
  };
  userGamesQuery = async ({
    cursor,
    limit,
    userAddress
  }: {
    cursor?: number;
    limit: number;
    userAddress: Addr;
  }): Promise<QueryUserGamesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_games_query: {
        cursor,
        limit,
        user_address: userAddress
      }
    });
  };
}
export interface RollADiceInterface extends RollADiceReadOnlyInterface {
  contractAddress: string;
  sender: string;
  setConfig: ({
    acceptedDenom,
    disabled,
    feePercentage,
    gasLimit,
    maxBet,
    minBet,
    operator,
    randomCwAddress
  }: {
    acceptedDenom: string;
    disabled: boolean;
    feePercentage: string;
    gasLimit: string;
    maxBet: string;
    minBet: string;
    operator?: Addr;
    randomCwAddress: Addr;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  playRequest: ({
    gameType
  }: {
    gameType: GameType;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  receiveRandomness: ({
    id,
    results
  }: {
    id: Uint64;
    results: JobResult[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  fetchRandomCWConfig: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    amount,
    token
  }: {
    amount: string;
    token: Token;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class RollADiceClient extends RollADiceQueryClient implements RollADiceInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setConfig = this.setConfig.bind(this);
    this.playRequest = this.playRequest.bind(this);
    this.receiveRandomness = this.receiveRandomness.bind(this);
    this.fetchRandomCWConfig = this.fetchRandomCWConfig.bind(this);
    this.withdraw = this.withdraw.bind(this);
  }
  setConfig = async ({
    acceptedDenom,
    disabled,
    feePercentage,
    gasLimit,
    maxBet,
    minBet,
    operator,
    randomCwAddress
  }: {
    acceptedDenom: string;
    disabled: boolean;
    feePercentage: string;
    gasLimit: string;
    maxBet: string;
    minBet: string;
    operator?: Addr;
    randomCwAddress: Addr;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_config: {
        accepted_denom: acceptedDenom,
        disabled,
        fee_percentage: feePercentage,
        gas_limit: gasLimit,
        max_bet: maxBet,
        min_bet: minBet,
        operator,
        random_cw_address: randomCwAddress
      }
    }, fee_, memo_, funds_);
  };
  playRequest = async ({
    gameType
  }: {
    gameType: GameType;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      play_request: {
        game_type: gameType
      }
    }, fee_, memo_, funds_);
  };
  receiveRandomness = async ({
    id,
    results
  }: {
    id: Uint64;
    results: JobResult[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive_randomness: {
        id,
        results
      }
    }, fee_, memo_, funds_);
  };
  fetchRandomCWConfig = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      fetch_random_c_w_config: {}
    }, fee_, memo_, funds_);
  };
  withdraw = async ({
    amount,
    token
  }: {
    amount: string;
    token: Token;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        amount,
        token
      }
    }, fee_, memo_, funds_);
  };
}